-- 360Ghar Initial Schema
-- Consolidated migration for complete database setup

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create custom ENUM types
CREATE TYPE property_type AS ENUM ('house', 'apartment', 'builder_floor', 'room');
CREATE TYPE property_purpose AS ENUM ('buy', 'rent', 'short_stay');
CREATE TYPE property_status AS ENUM ('available', 'sold', 'rented', 'under_offer', 'maintenance');
CREATE TYPE booking_status AS ENUM ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'completed');
CREATE TYPE payment_status AS ENUM ('pending', 'partial', 'paid', 'refunded', 'failed');
CREATE TYPE visit_status AS ENUM ('scheduled', 'confirmed', 'completed', 'cancelled', 'rescheduled');

-- Users table linked to Supabase Auth
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supabase_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) UNIQUE,
    full_name VARCHAR(255),
    date_of_birth DATE,
    profile_image_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    is_verified BOOLEAN DEFAULT FALSE,
    
    -- User preferences for property recommendations
    preferences JSONB,
    
    -- Location data for geo-based recommendations
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    preferred_locations JSONB,
    
    -- Notification settings
    notification_settings JSONB DEFAULT '{"email_notifications": true, "push_notifications": true, "sms_notifications": false}',
    
    -- Privacy settings
    privacy_settings JSONB DEFAULT '{"profile_visibility": "public", "location_sharing": true}',
    
    -- Agent assignment (will be added after agents table is created)
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Properties table
CREATE TABLE IF NOT EXISTS public.properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    property_type property_type NOT NULL,
    purpose property_purpose NOT NULL,
    status property_status DEFAULT 'available',
    
    -- Location data
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100) DEFAULT 'India',
    pincode VARCHAR(10),
    locality VARCHAR(150),
    sub_locality VARCHAR(150),
    landmark VARCHAR(255),
    full_address TEXT,
    area_type VARCHAR(100),
    
    -- Pricing
    base_price NUMERIC(12, 2) NOT NULL,
    price_per_sqft NUMERIC(10, 2),
    monthly_rent NUMERIC(10, 2),
    daily_rate NUMERIC(10, 2),
    security_deposit NUMERIC(10, 2),
    maintenance_charges NUMERIC(10, 2),
    
    -- Property details
    area_sqft NUMERIC(10, 2),
    bedrooms INTEGER,
    bathrooms INTEGER,
    balconies INTEGER,
    parking_spaces INTEGER,
    floor_number INTEGER,
    total_floors INTEGER,
    age_of_property INTEGER,
    
    -- For short stay properties
    max_occupancy INTEGER,
    minimum_stay_days INTEGER DEFAULT 1,
    
    -- Amenities and features
    amenities JSONB,
    features JSONB,
    
    -- Media
    main_image_url TEXT,
    virtual_tour_url TEXT,
    
    -- Availability and booking
    is_available BOOLEAN DEFAULT TRUE,
    available_from VARCHAR(50),
    calendar_data JSONB,
    
    -- SEO and search
    tags JSONB,
    search_keywords TEXT,
    
    -- Owner/Builder information
    owner_name VARCHAR(255),
    owner_contact VARCHAR(50),
    builder_name VARCHAR(255),
    
    -- Performance metrics
    view_count INTEGER DEFAULT 0,
    like_count INTEGER DEFAULT 0,
    interest_count INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Property images table
CREATE TABLE IF NOT EXISTS public.property_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    caption TEXT,
    display_order INTEGER DEFAULT 0,
    is_main_image BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Agents table (360Ghar employee agents)
CREATE TABLE IF NOT EXISTS public.agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Agent identity
    name VARCHAR(255) NOT NULL,
    agent_code VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    avatar_url TEXT,
    
    -- Agent capabilities and personality
    personality_traits JSONB DEFAULT '{}',
    specializations JSONB DEFAULT '[]',
    languages JSONB DEFAULT '["english"]',
    
    -- Agent configuration
    agent_type VARCHAR(50) DEFAULT 'general',
    experience_level VARCHAR(20) DEFAULT 'intermediate',
    max_concurrent_users INTEGER DEFAULT 50,
    
    -- AI/Bot configuration
    ai_model VARCHAR(100) DEFAULT 'gpt-4',
    system_prompt TEXT,
    response_style VARCHAR(50) DEFAULT 'conversational',
    
    -- Performance and availability
    is_active BOOLEAN DEFAULT TRUE,
    is_available BOOLEAN DEFAULT TRUE,
    working_hours JSONB DEFAULT '{"start": "09:00", "end": "18:00", "timezone": "UTC"}',
    
    -- Statistics
    total_users_assigned INTEGER DEFAULT 0,
    total_interactions INTEGER DEFAULT 0,
    average_response_time_seconds INTEGER DEFAULT 30,
    user_satisfaction_rating NUMERIC(3, 2) DEFAULT 0.0,
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    last_active_at TIMESTAMPTZ
);

-- Add agent_id column to users table
ALTER TABLE public.users 
ADD COLUMN agent_id BIGINT REFERENCES public.agents(id);

-- User swipes table
CREATE TABLE IF NOT EXISTS public.user_swipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    property_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    is_liked BOOLEAN NOT NULL,
    swipe_timestamp TIMESTAMPTZ DEFAULT NOW(),
    
    -- Additional context
    user_location_lat DOUBLE PRECISION,
    user_location_lng DOUBLE PRECISION,
    session_id VARCHAR(255),
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    
    -- Ensure a user can only swipe on a property once
    UNIQUE (user_id, property_id)
);

-- User favorites table
CREATE TABLE IF NOT EXISTS public.user_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    property_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    is_favorite BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    
    UNIQUE (user_id, property_id)
);

-- User search history table
CREATE TABLE IF NOT EXISTS public.user_search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    search_query VARCHAR(255),
    search_filters JSONB,
    search_location VARCHAR(255),
    search_radius INTEGER,
    results_count INTEGER,
    
    -- User's location during search
    user_location_lat DOUBLE PRECISION,
    user_location_lng DOUBLE PRECISION,
    
    -- Search context
    search_type VARCHAR(50),
    session_id VARCHAR(255),
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Visits table
CREATE TABLE IF NOT EXISTS public.visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    property_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    agent_id BIGINT REFERENCES public.agents(id),
    
    -- Visit details
    scheduled_date TIMESTAMPTZ NOT NULL,
    actual_date TIMESTAMPTZ,
    status visit_status DEFAULT 'scheduled',
    
    -- Visit preferences
    special_requirements TEXT,
    
    -- Visit outcome
    visit_notes TEXT,
    visitor_feedback TEXT,
    interest_level VARCHAR(50),
    follow_up_required BOOLEAN DEFAULT FALSE,
    follow_up_date TIMESTAMPTZ,
    
    -- Cancellation/Rescheduling
    cancellation_reason TEXT,
    rescheduled_from TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Bookings table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    property_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    
    -- Booking details
    booking_reference VARCHAR(50) UNIQUE NOT NULL,
    check_in_date TIMESTAMPTZ NOT NULL,
    check_out_date TIMESTAMPTZ NOT NULL,
    nights INTEGER NOT NULL,
    guests INTEGER NOT NULL,
    
    -- Pricing
    base_amount NUMERIC(10, 2) NOT NULL,
    taxes_amount NUMERIC(10, 2) DEFAULT 0,
    service_charges NUMERIC(10, 2) DEFAULT 0,
    discount_amount NUMERIC(10, 2) DEFAULT 0,
    total_amount NUMERIC(10, 2) NOT NULL,
    
    -- Status
    booking_status booking_status DEFAULT 'pending',
    payment_status payment_status DEFAULT 'pending',
    
    -- Guest information
    primary_guest_name VARCHAR(255) NOT NULL,
    primary_guest_phone VARCHAR(20) NOT NULL,
    primary_guest_email VARCHAR(255) NOT NULL,
    guest_details JSONB,
    
    -- Special requests and notes
    special_requests TEXT,
    internal_notes TEXT,
    
    -- Check-in/out details
    actual_check_in TIMESTAMPTZ,
    actual_check_out TIMESTAMPTZ,
    early_check_in BOOLEAN DEFAULT FALSE,
    late_check_out BOOLEAN DEFAULT FALSE,
    
    -- Cancellation
    cancellation_date TIMESTAMPTZ,
    cancellation_reason TEXT,
    refund_amount NUMERIC(10, 2),
    
    -- Payment details
    payment_method VARCHAR(100),
    transaction_id VARCHAR(255),
    payment_date TIMESTAMPTZ,
    
    -- Reviews and ratings
    guest_rating INTEGER CHECK (guest_rating >= 1 AND guest_rating <= 5),
    guest_review TEXT,
    host_rating INTEGER CHECK (host_rating >= 1 AND host_rating <= 5),
    host_review TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Comments for documentation
COMMENT ON TABLE public.agents IS '360Ghar employee agents who assist users';
COMMENT ON COLUMN public.agents.agent_code IS 'Unique identifier for the agent (e.g., AGENT_001)';
COMMENT ON COLUMN public.agents.personality_traits IS 'JSON object defining agent personality characteristics';
COMMENT ON COLUMN public.agents.specializations IS 'Array of agent specialization areas';
COMMENT ON COLUMN public.users.agent_id IS 'Assigned 360Ghar employee agent for this user';
COMMENT ON COLUMN public.visits.agent_id IS 'Agent coordinating this visit';